### ISSUE TITLE
dockerfile caches for update

### ISSUE THREAD

**Issue by covingto** [ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools#13]
This is not a recommended sequence in the dockerfile depending on your cache settings:

RUN apt-get update
RUN apt list upgradable
RUN apt-get upgrade -y
RUN apt-get install -y git tabix gcc make zlib1g-dev libstring-random-perl

http://crosbymichael.com/dockerfile-best-practices-take-2.html
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run

instead I think it should be 
RUN apt-get update && apt-get install -y \
  git \
  tabix \
  gcc \
  make \
  ...

**Comment by SolomonShorser-OICR** [comment]
Dockerfile now builds in a better sequence.
