### ISSUE TITLE
Remove unneeded 'oxoQScore' input field in oxog_varbam_annotate_wf.cwl

### ISSUE THREAD

**Issue by junjun-zhang** [ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools#22]
This `oxoQScore` field at here: 
https://github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/blob/develop/oxog_varbam_annotate_wf.cwl#L46-L47, has been moved to https://github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/blob/develop/TumourType.yaml#L16-L19

Need to be removed

**Comment by SolomonShorser-OICR** [comment]
Good point. Fixed, see: https://github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/commit/013eee1c48466f9e469052d3560e45a4063bae47
